apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: react-frontend
  name: react-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: react-frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: react-frontend
    spec:
      containers:
        - image: veredmazor/finel-project-react-frontend
          name: react-frontend
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
