apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: spark-als-model
  name: spark-als-model
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-als-model
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: spark-als-model
    spec:
      containers:
        - image: veredmazor/finel-project-spark-als-model
          name: spark-als
      restartPolicy: Always
